@php
    $reportFooter = $reportFooter ?? ($branding['reportFooter'] ?? null);
    $companyName = $companyName ?? ($branding['companyName'] ?? 'Performance Appraisal Studio');
    $poweredByExists = $poweredByExists ?? ($branding['poweredByExists'] ?? false);
    $poweredByPath = $poweredByPath ?? ($branding['poweredByPath'] ?? null);
    $poweredByUrl = $poweredByUrl ?? ($branding['poweredByUrl'] ?? null);
    $poweredBySrc = ($previewHtml ?? false)
        ? ($poweredByUrl ?? $poweredByPath)
        : ($poweredByPath ?? $poweredByUrl);
@endphp
<div class="footer">
    <table class="footer-table">
        <tr>
            <td class="footer-main">
                @if ($reportFooter)
                    {{ $reportFooter }}<br>
                @endif
                @if (isset($exportedBy) && isset($exportedAt))
                    Generated by {{ $exportedBy }} on {{ $exportedAt->format('d M Y H:i') }}.
                @else
                    {{ $companyName }} | Generated {{ optional($exportedAt ?? now())->format('d M Y H:i') }}
                @endif
            </td>
            @if ($poweredByExists && $poweredBySrc)
                <td class="footer-powered powered-by">
                    <span class="label">Powered by</span>
                    <img src="{{ $poweredBySrc }}" alt="TJT">
                </td>
            @endif
        </tr>
    </table>
</div>
