@php
    use App\Support\Branding;

    $brandingContext = $branding ?? [];
    $reportFooter = $reportFooter ?? ($brandingContext['reportFooter'] ?? null);
    $companyName = $companyName ?? ($brandingContext['companyName'] ?? 'Performance Appraisal Studio');
    $poweredByExists = $poweredByExists ?? ($brandingContext['poweredByExists'] ?? false);
    $poweredByPath = $poweredByPath ?? ($brandingContext['poweredByPath'] ?? null);
    $poweredByUrl = $poweredByUrl ?? ($brandingContext['poweredByUrl'] ?? null);
    $poweredByDataUri = $poweredByDataUri ?? ($brandingContext['poweredByDataUri'] ?? null);
    $poweredByPdfSrc = $poweredByPdfSrc ?? ($brandingContext['poweredByPdfSrc'] ?? null);

    if (! filled($poweredByPdfSrc) && filled($poweredByPath)) {
        $poweredByPdfSrc = Branding::pdfImageSrc($poweredByPath);
    }

    if (! filled($poweredByDataUri) && filled($poweredByPath)) {
        $poweredByDataUri = Branding::imageDataUriForPath($poweredByPath);
    }

    $poweredByExists = $poweredByExists || filled($poweredByPdfSrc) || filled($poweredByDataUri) || filled($poweredByUrl);

    $poweredBySrc = ($previewHtml ?? false)
        ? ($poweredByUrl ?? $poweredByDataUri ?? $poweredByPdfSrc)
        : ($poweredByPdfSrc ?? $poweredByDataUri ?? $poweredByUrl);
@endphp
<div class="footer">
    <table class="footer-table">
        <tr>
            <td class="footer-main">
                @if ($reportFooter)
                    {{ $reportFooter }}<br>
                @endif
                @if (isset($exportedBy) && isset($exportedAt))
                    Generated by {{ $exportedBy }} on {{ $exportedAt->format('d M Y H:i') }}.
                @else
                    {{ $companyName }} | Generated {{ optional($exportedAt ?? now())->format('d M Y H:i') }}
                @endif
            </td>
            @if ($poweredByExists && $poweredBySrc)
                <td class="footer-powered powered-by">
                    <span class="label">Powered by</span>
                    <img src="{{ $poweredBySrc }}" alt="TJT">
                </td>
            @endif
        </tr>
    </table>
</div>
